/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sd_205_mongodb;

import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
//        setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cenomarBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        birthBtn = new javax.swing.JButton();
        marriageBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        homeBtn = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        scholarshipBtn = new javax.swing.JButton();
        deathBtn = new javax.swing.JButton();
        businessBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        suggestionsBtn = new javax.swing.JButton();
        votersBtn = new javax.swing.JButton();
        appointmentBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        minimize = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/scholarship.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 320, 190, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/merriage.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 80, 180, 170));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cenomar.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 80, 200, 170));

        cenomarBtn.setText("CENOMAR");
        cenomarBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 3, true));
        cenomarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cenomarBtnMouseClicked(evt);
            }
        });
        jPanel1.add(cenomarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 280, 120, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 90));

        birthBtn.setText("Birth Certificate");
        birthBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 3, true));
        birthBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                birthBtnMouseClicked(evt);
            }
        });
        jPanel1.add(birthBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 120, 30));

        marriageBtn.setText("Marriage Certificate");
        marriageBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 3, true));
        marriageBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marriageBtnMouseClicked(evt);
            }
        });
        jPanel1.add(marriageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 280, 120, 30));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel6.setText("Sign-up");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 20, 80, 30));

        jComboBox1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Services", "Birth Certificate", "Marriage Certificate", "CENOMAR", "Death Certificate", "Business Permit", "Scholarship", "Voters Certificate", "Appointment", "Suggestions" }));
        jComboBox1.setBorder(null);
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 120, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 204, 0));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 550, 750, 20));

        homeBtn.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 60, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 20, 20, 30));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel8.setText("Sign-in");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 20, 60, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/birth.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 210, 190));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/death.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 550, 210, 190));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/permit.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 320, 210, 190));

        scholarshipBtn.setText("Scholarship");
        scholarshipBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 3, true));
        scholarshipBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scholarshipBtnMouseClicked(evt);
            }
        });
        jPanel1.add(scholarshipBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 510, 120, 30));

        deathBtn.setText("Death Certificate");
        deathBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 3, true));
        deathBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deathBtnMouseClicked(evt);
            }
        });
        jPanel1.add(deathBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 120, 30));

        businessBtn.setText("Business Permit");
        businessBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 3, true));
        businessBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                businessBtnMouseClicked(evt);
            }
        });
        jPanel1.add(businessBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 510, 120, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/death.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 210, 180));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/death.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 210, 190));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/death.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 550, 210, 190));

        suggestionsBtn.setText("Suggestions");
        suggestionsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 3, true));
        suggestionsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suggestionsBtnMouseClicked(evt);
            }
        });
        jPanel1.add(suggestionsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 750, 120, 30));

        votersBtn.setText("Voter's Certificate");
        votersBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 3, true));
        votersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                votersBtnMouseClicked(evt);
            }
        });
        jPanel1.add(votersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 750, 120, 30));

        appointmentBtn.setText("Appointment");
        appointmentBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 3, true));
        appointmentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointmentBtnMouseClicked(evt);
            }
        });
        jPanel1.add(appointmentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 750, 120, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 1130, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 204, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 90, 10, 740));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 204, 0));
        jSeparator5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 750, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 204, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 204, 0));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 90, 10, 750));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel9.setText("CEBU CITY EASY PASSAGE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 380, 60));

        minimize.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minimize.setText("-");
        minimize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 0, 30, 30));

        closeBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closeBtn.setText("X");
        closeBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 0, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeBtnMouseClicked

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeActionPerformed

    private void birthBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_birthBtnMouseClicked
        BirthCertificate bc = new BirthCertificate();
        bc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_birthBtnMouseClicked

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnMouseClicked

    private void marriageBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marriageBtnMouseClicked
        MarriageCertificate mc = new MarriageCertificate();
        mc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_marriageBtnMouseClicked

    private void cenomarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cenomarBtnMouseClicked
        Cenomar c = new Cenomar();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cenomarBtnMouseClicked

    private void deathBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deathBtnMouseClicked
        DeathCertificate dc = new DeathCertificate();
        dc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deathBtnMouseClicked

    private void businessBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_businessBtnMouseClicked
//        BusinessPermit bp = new Businesspermit();
//        bp.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_businessBtnMouseClicked

    private void scholarshipBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scholarshipBtnMouseClicked
//       Scholarship s = new Scholarship();
//        s.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_scholarshipBtnMouseClicked

    private void votersBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_votersBtnMouseClicked
//        VotersCertificate vc = new VotersCertificate();
//        vc.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_votersBtnMouseClicked

    private void appointmentBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentBtnMouseClicked
        Appointment a = new Appointment();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_appointmentBtnMouseClicked

    private void suggestionsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suggestionsBtnMouseClicked
        Suggestion s = new Suggestion();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_suggestionsBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointmentBtn;
    private javax.swing.JButton birthBtn;
    private javax.swing.JButton businessBtn;
    private javax.swing.JButton cenomarBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton deathBtn;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton marriageBtn;
    private javax.swing.JButton minimize;
    private javax.swing.JButton scholarshipBtn;
    private javax.swing.JButton suggestionsBtn;
    private javax.swing.JButton votersBtn;
    // End of variables declaration//GEN-END:variables
}
